### ISSUE TITLE
Not found from URL and doesn't seem to exists

### ISSUE THREAD

**Issue by Starzilla29** [ExponentialML/AnimateDiff-MotionDirector#12]
After following the instructions for setup from the repo I get the following error:

```python
Traceback (most recent call last):
  File "/mnt/Samsung980Pro/arch_linux_software/anaconda3/envs/animatediff-motiondirector/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 286, in hf_raise_for_status
    response.raise_for_status()
  File "/mnt/Samsung980Pro/arch_linux_software/anaconda3/envs/animatediff-motiondirector/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/diffusers/stable-diffusion-v1-5/resolve/main/vae/diffusion_pytorch_model.bin

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/Samsung980Pro/arch_linux_software/anaconda3/envs/animatediff-motiondirector/lib/python3.10/site-packages/diffusers/modeling_utils.py", line 600, in _get_model_file
    model_file = hf_hub_download(
  File "/mnt/Samsung980Pro/arch_linux_software/anaconda3/envs/animatediff-motiondirector/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/mnt/Samsung980Pro/arch_linux_software/anaconda3/envs/animatediff-motiondirector/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1368, in hf_hub_download
    raise head_call_error
  File "/mnt/Samsung980Pro/arch_linux_software/anaconda3/envs/animatediff-motiondirector/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1238, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "/mnt/Samsung980Pro/arch_linux_software/anaconda3/envs/animatediff-motiondirector/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/mnt/Samsung980Pro/arch_linux_software/anaconda3/envs/animatediff-motiondirector/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1631, in get_hf_file_metadata
    r = _request_wrapper(
  File "/mnt/Samsung980Pro/arch_linux_software/anaconda3/envs/animatediff-motiondirector/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 385, in _request_wrapper
    response = _request_wrapper(
  File "/mnt/Samsung980Pro/arch_linux_software/anaconda3/envs/animatediff-motiondirector/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 409, in _request_wrapper
    hf_raise_for_status(response)
  File "/mnt/Samsung980Pro/arch_linux_software/anaconda3/envs/animatediff-motiondirector/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 323, in hf_raise_for_status
    raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 404 Client Error. (Request ID: Root=1-65c2558d-7ee52867429c7cb00573f23b;01245222-2121-417b-a172-779cf0e57f42)

Repository Not Found for url: https://huggingface.co/diffusers/stable-diffusion-v1-5/resolve/main/vae/diffusion_pytorch_model.bin.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/Samsung980Pro/WORK/AI/arch/AnimateDiff-MotionDirector/train.py", line 1038, in <module>
    main(name=name, use_wandb=args.wandb, **config)
  File "/mnt/Samsung980Pro/WORK/AI/arch/AnimateDiff-MotionDirector/train.py", line 527, in main
    vae          = AutoencoderKL.from_pretrained(pretrained_model_path, subfolder="vae")
  File "/mnt/Samsung980Pro/arch_linux_software/anaconda3/envs/animatediff-motiondirector/lib/python3.10/site-packages/diffusers/modeling_utils.py", line 452, in from_pretrained
    model_file = cls._get_model_file(
  File "/mnt/Samsung980Pro/arch_linux_software/anaconda3/envs/animatediff-motiondirector/lib/python3.10/site-packages/diffusers/modeling_utils.py", line 616, in _get_model_file
    raise EnvironmentError(
OSError: diffusers/stable-diffusion-v1-5 is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo with `use_auth_token` or log in with `huggingface-cli login`.
``` 

Which is odd to me because I have the entire stable diffusion huggingface repo clone into "models/StableDiffusion" and when I try to follow the link to "https://huggingface.co/diffusers/stable-diffusion-v1-5/resolve/main/vae/diffusion_pytorch_model.bin" I get a repository not found, I try to search for this in hugging face specifcally and I still cannot find it even though I actually think this is trying to refer to "https://huggingface.co/runwayml/stable-diffusion-v1-5" which I already have installed I believe under the correct folder structure. What am I missing here?

**Comment by Starzilla29** [comment]
I feel a bit dumb, I needed to change "pretrained_model_path: diffusers/stable-diffusion-v1-5" to "pretrained_model_path: models/StableDiffusion/", but not going to lie, I didn't think that would be something I would need to mess with.

**Comment by rodsott** [comment]
for this download to work I changed at the my_video.yaml file the second line to:
**pretrained_model_path: "runwayml/stable-diffusion-v1-5"** Then it downloaded it. Seems they really removed those files from that repo.

**Comment by mhussar** [comment]
why can't we just manually download the checkpoints and dispense with the whole downloading from huggingface part.

**Comment by mhussar** [comment]
does anyone know in what script its trying to reach hugging face?

**Comment by C0nsumption** [comment]
Does anyone know is that answer to this? this is so aggravating.

**Comment by C0nsumption** [comment]
pretrained_model_path: "models/StableDiffusion/stable-diffusion-v1-5"

Thats the answer. Update the dang instructions man.
