### ISSUE TITLE
Issue with running repo

### ISSUE THREAD

**Issue by filliptm** [ExponentialML/AnimateDiff-MotionDirector#2]
![image](https://github.com/ExponentialML/AnimateDiff-MotionDirector/assets/55672949/be347e53-deb3-4fd9-9ea2-88ec5c441c23)
![image](https://github.com/ExponentialML/AnimateDiff-MotionDirector/assets/55672949/5667585f-31eb-49f3-a044-e39abd6d6a5f)

**Comment by ExponentialML** [comment]
Hi. Could you try installing the following and see if it solves the issue?

```bash
pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 torchaudio==0.13.1 xformers==0.0.16 --extra-index-url https://download.pytorch.org/whl/cu117
```

**Comment by rodsott** [comment]
I'm having the same problem. Using the latest versions installed with the requirements.txt, it gave me the following error:

 `WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.2.0+cu121 with CUDA 1201 (you have 2.2.0+cpu)
    Python  3.10.11 (you have 3.10.13)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details`

and using the above suggestion, it gave the triton missing message:

`A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
`
...and installing the pytorch-triton, it gave this error:

`Traceback (most recent call last):
  File "X:\ai\AnimateDiff-MotionDirector\train.py", line 20, in <module>
    import diffusers
  File "C:\Users\Admin\anaconda3\envs\AnimateDiff-MotionDirector\lib\site-packages\diffusers\__init__.py", line 28, in <module>
    from .models import (
  File "C:\Users\Admin\anaconda3\envs\AnimateDiff-MotionDirector\lib\site-packages\diffusers\models\__init__.py", line 19, in <module>
    from .attention import Transformer2DModel
  File "C:\Users\Admin\anaconda3\envs\AnimateDiff-MotionDirector\lib\site-packages\diffusers\models\attention.py", line 43, in <module>
    import xformers.ops
  File "C:\Users\Admin\anaconda3\envs\AnimateDiff-MotionDirector\lib\site-packages\xformers\ops\__init__.py", line 8, in <module>
    from .fmha import (
  File "C:\Users\Admin\anaconda3\envs\AnimateDiff-MotionDirector\lib\site-packages\xformers\ops\fmha\__init__.py", line 10, in <module>
    from . import cutlass, flash, small_k, triton
  File "C:\Users\Admin\anaconda3\envs\AnimateDiff-MotionDirector\lib\site-packages\xformers\ops\fmha\triton.py", line 15, in <module>
    if TYPE_CHECKING or _is_triton_available():
  File "C:\Users\Admin\anaconda3\envs\AnimateDiff-MotionDirector\lib\site-packages\xformers\__init__.py", line 33, in func_wrapper
    value = func()
  File "C:\Users\Admin\anaconda3\envs\AnimateDiff-MotionDirector\lib\site-packages\xformers\__init__.py", line 44, in _is_triton_available
    from xformers.triton.softmax import softmax as triton_softmax  # noqa
  File "C:\Users\Admin\anaconda3\envs\AnimateDiff-MotionDirector\lib\site-packages\xformers\triton\__init__.py", line 12, in <module>
    from .dropout import FusedDropoutBias, dropout  # noqa
  File "C:\Users\Admin\anaconda3\envs\AnimateDiff-MotionDirector\lib\site-packages\xformers\triton\dropout.py", line 13, in <module>
    import triton
  File "C:\Users\Admin\anaconda3\envs\AnimateDiff-MotionDirector\lib\site-packages\triton\__init__.py", line 1, in <module>
    raise RuntimeError("Should never be installed")
RuntimeError: Should never be installed
`

Any clue? Thanks in advance! Really eager to test your amazing code!! ^_^

**Comment by nicholasVANDAL** [comment]
I followed the instructions in https://github.com/ExponentialML/AnimateDiff-MotionDirector/issues/2#issuecomment-1924654048 as i had the same issue as above.

I now have the triton missing issue also (running windows 11)
However it is still running the training on cpu it seems. 

I do have a threadripper pro 5955WX and 124gb ram so thats probably carrying it also.
